packages:
  python-tmt-cmake:
    upstream_package_name: tmt-cmake
    # Need to define these
    # https://github.com/packit/packit/issues/2272
    downstream_package_name: python-tmt-cmake
    specfile_path: .distro/python-tmt-cmake.spec
    files_to_sync:
      - src: .distro/python-tmt-cmake.spec
        dest: python-tmt-cmake.spec
      - .packit.yaml
      - src: .distro/python-tmt-cmake.rpmlintrc
        dest: python-tmt-cmake.rpmlintrc
      # tmt setup
      - src: .distro/.fmf/
        dest: .fmf/
      - src: .distro/plans/
        dest: plans/
        filters:
          - "- main.fmf.dist-git"
          - "- rpminspect.fmf"
          - "- rpmlint.fmf"
      - src: .distro/tests/
        dest: tests/
      - src: .distro/plans/main.fmf.dist-git
        dest: plans/main.fmf

update_release: false
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    trigger: commit
    branch: main
    owner: lecris
    project: nightly
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
  - &tests
    job: tests
    trigger: commit
    branch: main
    targets:
      - fedora-all-x86_64
      - fedora-all-aarch64
    fmf_path: .distro
  - <<: *copr
    trigger: pull_request
    project: tmt-cmake
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
  - <<: *tests
    trigger: pull_request
  - <<: *copr
    trigger: release
    project: release
  - <<: *tests
    trigger: release
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
