files_to_sync:
  - src: .distro/
    dest: ./
    delete: true
    filters:
      - "protect .git*"
      - "protect sources"
      - "- plans/rpminspect.fmf"
      - "- plans/rpmlint.fmf"

upstream_package_name: tmt-cmake
downstream_package_name: python-tmt-cmake
specfile_path: .distro/python-tmt-cmake.spec

update_release: false
upstream_tag_template: v{version}

jobs:
  - &copr
    job: copr_build
    trigger: release
    owner: lecris
    project: release
    targets: &targets
      - fedora-all-x86_64
      - fedora-all-aarch64
  - &tests
    job: tests
    trigger: release
    targets: *targets
    fmf_path: .distro
  - <<: *copr
    trigger: commit
    project: nightly
    branch: main
    additional_repos:
      - copr://@scikit-build/release
  - <<: *tests
    trigger: commit
    branch: main
  - <<: *copr
    trigger: pull_request
    project: tmt-cmake
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
  - <<: *tests
    trigger: pull_request
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
